services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=${PGDATABASE_USER}
      - POSTGRES_PASSWORD=${PGDATABASE_PASSWORD}
      - POSTGRES_DB=${PGDATABASE_DB}
    volumes:
      - "./data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"